# Generated by Django 4.1.6 on 2023-02-13 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='certificate', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Glazing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=20, verbose_name='Артикул')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('percent', models.FloatField(verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Стеклопакет',
                'verbose_name_plural': 'Стеклопакеты',
            },
        ),
        migrations.CreateModel(
            name='Implement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('country', models.CharField(max_length=30, verbose_name='Страна производителя')),
                ('generator', models.CharField(max_length=30, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Фурнитура',
                'verbose_name_plural': 'Фурнитуры',
            },
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='learn/instructions', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
            },
        ),
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='learn/materials', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Учебные материал',
                'verbose_name_plural': 'Учебные материалы',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новинка',
                'verbose_name_plural': 'Новинки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=40, verbose_name='Регион')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Логистика',
                'verbose_name_plural': 'Логистика',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='shape/img', verbose_name='Фото')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('warm_proofing', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('sound_proofing', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('camera', models.IntegerField()),
                ('shape_width', models.CharField(max_length=10)),
                ('shape_height', models.CharField(max_length=10)),
                ('width_glaze', models.CharField(max_length=10)),
                ('warm_proofing_dc', models.CharField(max_length=10)),
                ('sound_proofing_dc', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Профильная система',
                'verbose_name_plural': 'Профильные системы',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='store/img', verbose_name='Фото')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('price_of_bonus', models.PositiveIntegerField(verbose_name='Цена в бонусах')),
                ('price', models.PositiveIntegerField(verbose_name='Цена в рублях')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазин',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='learn/video', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Видео обучение',
                'verbose_name_plural': 'Видео обучение',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('glazing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.glazing')),
                ('implement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.implement')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shape')),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
                'verbose_name_plural': 'Коммерческие предложения',
            },
        ),
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('photo', models.FileField(upload_to='employ', verbose_name='Фото')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Diler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('alert_phone', models.CharField(default='', max_length=12, verbose_name='Телефон для уведомлений')),
                ('address', models.CharField(default='', max_length=200, verbose_name='Адрес')),
                ('discount_window', models.IntegerField(default=0, verbose_name='Дилер')),
                ('accessories_discount', models.IntegerField(default=0, verbose_name='Дилер')),
                ('manager', models.CharField(default='', max_length=100, verbose_name='Дилер')),
                ('calculator', models.CharField(default='', max_length=100, verbose_name='Дилер')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Дилер')),
                ('last_week_bonus', models.FloatField(default=0, verbose_name='Дилер')),
                ('bonus', models.FloatField(default=0, verbose_name='Дилер')),
                ('sms_alert', models.BooleanField(default=False, verbose_name='Дилер')),
                ('telegram_alert', models.BooleanField(default=False, verbose_name='Дилер')),
                ('email_alert', models.BooleanField(default=False, verbose_name='Дилер')),
                ('change_mail', models.BooleanField(default=False, verbose_name='Дилер')),
                ('change_email', models.BooleanField(default=False, verbose_name='Дилер')),
                ('change_manager', models.BooleanField(default=False, verbose_name='Дилер')),
                ('ads_client', models.BooleanField(default=False, verbose_name='Дилер')),
                ('ads_me', models.BooleanField(default=False, verbose_name='Дилер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Дилер')),
            ],
            options={
                'verbose_name': 'Дилер',
                'verbose_name_plural': 'Дилеры',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveIntegerField()),
                ('count', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
            },
        ),
    ]
