# Generated by Django 4.1.6 on 2023-03-28 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(upload_to='certificate', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Glazing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=20, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('percent', models.FloatField(verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Стеклопакет',
                'verbose_name_plural': 'Стеклопакеты',
            },
        ),
        migrations.CreateModel(
            name='Implement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Название')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Страна производителя')),
                ('generator', models.CharField(max_length=30, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Фурнитура',
                'verbose_name_plural': 'Фурнитуры',
            },
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(upload_to='learn/instructions', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
            },
        ),
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(upload_to='learn/materials', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Учебные материал',
                'verbose_name_plural': 'Учебные материалы',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(upload_to='news', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=40, unique=True, verbose_name='Регион')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Логистика',
                'verbose_name_plural': 'Логистика',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sample')),
            ],
            options={
                'verbose_name': 'Акт замеров',
                'verbose_name_plural': 'Акт замеров',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='shape/img', verbose_name='Фото 303x323')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Название')),
                ('warm_proofing', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Теплоизоляция')),
                ('sound_proofing', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Шумоизоляция')),
                ('camera', models.IntegerField(verbose_name='Количество камер')),
                ('shape_width', models.CharField(max_length=10, verbose_name='Ширина профиля')),
                ('shape_height', models.CharField(max_length=10, verbose_name='Высота рамы')),
                ('width_glaze', models.CharField(max_length=10, verbose_name='Ширина стеклопакета')),
                ('warm_proofing_dc', models.CharField(max_length=10, verbose_name='Сопротивление теплопередачи в Дц')),
                ('sound_proofing_dc', models.CharField(max_length=10, verbose_name='Шумоизоляция в Дц')),
            ],
            options={
                'verbose_name': 'Профильная система',
                'verbose_name_plural': 'Профильные системы',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='store/img', verbose_name='Фото 303x323')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('count', models.IntegerField(verbose_name='В наличии')),
                ('price_of_bonus', models.PositiveIntegerField(verbose_name='Цена в бонусах')),
                ('price', models.PositiveIntegerField(verbose_name='Цена в рублях')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазин',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(upload_to='learn/video', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Видео обучение',
                'verbose_name_plural': 'Видео обучение',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='Размер')),
                ('price', models.PositiveIntegerField(verbose_name='Базовая цена')),
                ('glazing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.glazing', verbose_name='Стеклопакет')),
                ('implement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.implement', verbose_name='Фурнитура')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shape', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
                'verbose_name_plural': 'Коммерческие предложения',
            },
        ),
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('photo', models.FileField(upload_to='employ', verbose_name='Фото 303x323')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Diler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='Название компании')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Телефон')),
                ('alert_phone', models.CharField(default='', max_length=12, verbose_name='Телефон для уведомлений')),
                ('address', models.CharField(default='', max_length=200, verbose_name='Адрес')),
                ('discount_window', models.IntegerField(default=0, verbose_name='Скидка на окна')),
                ('accessories_discount', models.IntegerField(default=0, verbose_name='Скидка на аксессуары')),
                ('manager', models.CharField(default='', max_length=100, verbose_name='Территориальный менеджер')),
                ('calculator', models.CharField(default='', max_length=100, verbose_name='Расчетчик')),
                ('last_login', models.DateTimeField(verbose_name='Дата последнего входа')),
                ('bonus', models.FloatField(default=0, verbose_name='Бонусы дилера')),
                ('seller_code', models.CharField(max_length=20)),
                ('sms_alert', models.BooleanField(default=False, verbose_name='SMS')),
                ('telegram_alert', models.BooleanField(default=False, verbose_name='Telegram')),
                ('email_alert', models.BooleanField(default=False, verbose_name='E-mail')),
                ('change_mail', models.BooleanField(default=False, verbose_name='Отправка по почте')),
                ('change_email', models.BooleanField(default=False, verbose_name='Отправка по e-mail')),
                ('change_manager', models.BooleanField(default=False, verbose_name='Менеджером в руки')),
                ('ads_client', models.BooleanField(default=False, verbose_name='Решение с клиентом')),
                ('ads_me', models.BooleanField(default=False, verbose_name='Решение через меня')),
                ('cart', models.JSONField(default={})),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Дилер')),
            ],
            options={
                'verbose_name': 'Дилер',
                'verbose_name_plural': 'Дилеры',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr', models.DateField(verbose_name='Период от')),
                ('to', models.DateField(verbose_name='Период до')),
                ('select', models.CharField(choices=[('s', 'Профиль'), ('i', 'Фурнитура'), ('g', 'Стеклопакет')], max_length=10)),
                ('unit', models.CharField(choices=[('m2', 'm2'), ('шт', 'шт')], max_length=5, verbose_name='Единица измерения')),
                ('count', models.FloatField(verbose_name='Бонусы')),
                ('glazing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.glazing', verbose_name='Стеклопакет')),
                ('implement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.implement', verbose_name='Фурнитура')),
                ('shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shape', verbose_name='Профильная система')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
