# Generated by Django 4.1.6 on 2023-02-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.RemoveField(
            model_name='diler',
            name='last_week_bonus',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='count',
            field=models.FloatField(verbose_name='Бонусы'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='accessories_discount',
            field=models.IntegerField(default=0, verbose_name='Скидка на аксессуары'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='ads_client',
            field=models.BooleanField(default=False, verbose_name='Решение с клиентом'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='ads_me',
            field=models.BooleanField(default=False, verbose_name='Решение через меня'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='bonus',
            field=models.FloatField(default=0, verbose_name='Бонусы дилера'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='calculator',
            field=models.CharField(default='', max_length=100, verbose_name='Расчетчик'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='change_email',
            field=models.BooleanField(default=False, verbose_name='Отправка по e-mail'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='change_mail',
            field=models.BooleanField(default=False, verbose_name='Отправка по почте'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='change_manager',
            field=models.BooleanField(default=False, verbose_name='Менеджером в руки'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='discount_window',
            field=models.IntegerField(default=0, verbose_name='Скидка на окна'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='email_alert',
            field=models.BooleanField(default=False, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего входа'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='manager',
            field=models.CharField(default='', max_length=100, verbose_name='Территориальный менеджер'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='sms_alert',
            field=models.BooleanField(default=False, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='telegram_alert',
            field=models.BooleanField(default=False, verbose_name='SMS'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='learn',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='glazing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.glazing', verbose_name='Стеклопакет'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='implement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.implement', verbose_name='Фурнитура'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shape', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='size',
            field=models.CharField(max_length=20, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='camera',
            field=models.IntegerField(verbose_name='Количество камер'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='shape_height',
            field=models.CharField(max_length=10, verbose_name='Высота рамы'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='shape_width',
            field=models.CharField(max_length=10, verbose_name='Ширина профиля'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='sound_proofing',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Шумоизоляция'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='sound_proofing_dc',
            field=models.CharField(max_length=10, verbose_name='Шумоизоляция в Дц'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='warm_proofing',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Теплоизоляция'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='warm_proofing_dc',
            field=models.CharField(max_length=10, verbose_name='Сопротивление теплопередачи в Дц'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='width_glaze',
            field=models.CharField(max_length=10, verbose_name='Ширина стеклопакета'),
        ),
        migrations.AlterField(
            model_name='store',
            name='count',
            field=models.IntegerField(verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='Единица измерения'),
        ),
    ]
