# Generated by Django 4.1.6 on 2023-03-27 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='fr',
            field=models.DateField(verbose_name='Период от'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='glazing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.glazing', verbose_name='Стеклопакет'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='implement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.implement', verbose_name='Фурнитура'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shape', verbose_name='Профильная система'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='to',
            field=models.DateField(verbose_name='Период до'),
        ),
    ]
