# Generated by Django 4.1.6 on 2023-03-10 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='passports')),
                ('diler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diler')),
            ],
            options={
                'verbose_name': 'Паспорт качества',
                'verbose_name_plural': 'Паспорты качества',
            },
        ),
    ]
