# Generated by Django 4.1.6 on 2023-04-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_diler_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='zone',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
