# Generated by Django 4.1.6 on 2023-03-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passports'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='file',
            field=models.FileField(default=None, upload_to='news', verbose_name='Файл'),
            preserve_default=False,
        ),
    ]
