# Generated by Django 4.1.6 on 2023-05-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bonus_shape_alter_offers_shape_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DilerBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_code', models.CharField(max_length=20, unique=True)),
                ('total_bonus', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.RemoveField(
            model_name='diler',
            name='bonus',
        ),
        migrations.AlterField(
            model_name='diler',
            name='seller_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
