# Generated by Django 4.1.6 on 2023-05-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_shapesystem_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='photo',
            field=models.ImageField(upload_to='employ', verbose_name='Фото 303x323'),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=models.ImageField(upload_to='store/img', verbose_name='Фото 303x323'),
        ),
    ]
