# Generated by Django 4.1.6 on 2023-05-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_employ_photo_alter_store_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Расчетчик',
                'verbose_name_plural': 'Расчетчики',
            },
        ),
        migrations.CreateModel(
            name='TerritoryManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Территориальный менеджер',
                'verbose_name_plural': 'Территориальный менеджеры',
            },
        ),
        migrations.AlterField(
            model_name='employ',
            name='role',
            field=models.CharField(choices=[('director', 'Собственник'), ('development', 'Руководитель отдела развития'), ('calculator', 'Расчетчик'), ('service', 'Менеджер по рекламациям'), ('territory', 'Территориальный менеджер')], max_length=60),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='diler',
            name='calculator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculator', to='core.calculatemanager', verbose_name='Расчетчик'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='core.territorymanager', verbose_name='Территориальный менеджер'),
        ),
    ]
