# Generated by Django 4.1.6 on 2023-05-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_calculatemanager_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculatemanager',
            options={'verbose_name': 'Менеджер по расчетам'},
        ),
        migrations.AlterModelOptions(
            name='territorymanager',
            options={'verbose_name': 'Менеджер отдела развития'},
        ),
        migrations.AlterField(
            model_name='calculatemanager',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='calculatemanager',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employ', verbose_name='Фото 200x200'),
        ),
        migrations.AlterField(
            model_name='employ',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='employ',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employ', verbose_name='Фото 200x200'),
        ),
        migrations.AlterField(
            model_name='employ',
            name='role',
            field=models.CharField(choices=[('director', 'Собственник'), ('development', 'Руководитель отдела развития'), ('service', 'Руководитель отдела качества'), ('pricer', 'Руководитель отдела логистики')], max_length=60),
        ),
        migrations.AlterField(
            model_name='territorymanager',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='territorymanager',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employ', verbose_name='Фото 200x200'),
        ),
    ]
