# Generated by Django 4.1.6 on 2023-05-31 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_calculatemanager_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculatemanager',
            options={'verbose_name': 'Менеджер по расчетам', 'verbose_name_plural': 'Менеджер по расчетам'},
        ),
        migrations.AlterModelOptions(
            name='territorymanager',
            options={'verbose_name': 'Менеджер отдела развития', 'verbose_name_plural': 'Менеджер отдела развития'},
        ),
    ]
