# Generated by Django 4.1.6 on 2023-10-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_diler_address_alter_diler_alert_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diler',
            name='alert_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон для уведомлений'),
        ),
        migrations.AlterField(
            model_name='diler',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
